apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-components
  namespace: admin
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./infra/platform-engineering/components"
  prune: true
  interval: 5m
